# fly.toml app configuration file generated for ogame-commander

app = 'ogame-commander'
primary_region = 'cdg'

[build]

[env]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = "/usr/share/nginx/html"
  url_prefix = "/"
